/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/girl": {
    get: operations["GirlController_getGirls"];
  };
  "/api/juejin": {
    /** 获取稀土掘金热榜 */
    get: operations["JuejinController_getJuejin"];
  };
  "/api/juejin/new": {
    /** 获取最新稀土掘金热榜 */
    get: operations["JuejinController_getNewJuejin"];
  };
  "/api/36kr": {
    /** 获取36氪热榜 */
    get: operations["KrController_getKr"];
  };
  "/api/36kr/new": {
    /** 获取最新36氪热榜 */
    get: operations["KrController_getNewKr"];
  };
  "/api/baidu": {
    /** 获取百度热搜榜 */
    get: operations["BaiduController_getBaidu"];
  };
  "/api/baidu/new": {
    /** 获取百度热搜榜的最新数据 */
    get: operations["BaiduController_getNewBaidu"];
  };
  "/api/bilibili": {
    /** 获取哔哩哔哩热门榜 */
    get: operations["BilibiliController_getBilibili"];
  };
  "/api/zhihu": {
    /** 获取知乎热榜 */
    get: operations["ZhihuController_getZhihuHot"];
  };
  "/api/zhihu/new": {
    /** 获取最新的知乎热榜 */
    get: operations["ZhihuController_getZhihuHotNew"];
  };
  "/api/tieba": {
    /** 获取贴吧热议榜 */
    get: operations["TiebaController_getTieba"];
  };
  "/api/tieba/new": {
    /** 获取最新的贴吧热议榜 */
    get: operations["TiebaController_getNewTieba"];
  };
  "/api/thepaper": {
    /** 获取澎湃热榜 */
    get: operations["ThePaperController_getThePaper"];
  };
  "/api/thepaper/new": {
    /** 获取澎湃热榜 - 最新数据 */
    get: operations["ThePaperController_getNewThePaper"];
  };
  "/api/weibo": {
    /** 获取微博热搜 */
    get: operations["WeiboController_getWeibo"];
  };
  "/api/weibo/new": {
    /** 获取微博热搜 - 最新数据 */
    get: operations["WeiboController_getNewWeibo"];
  };
  "/api/sspai": {
    /** 获取少数派热榜 */
    get: operations["SspaiController_getSspai"];
  };
  "/api/sspai/new": {
    /** 获取少数派热榜 - 最新数据 */
    get: operations["SspaiController_getNewSspai"];
  };
  "/api/newsqq": {
    /** 获取腾讯热点榜 */
    get: operations["NewsqqController_getNewsqq"];
  };
  "/api/newsqq/new": {
    /** 获取腾讯热点榜 - 最新数据 */
    get: operations["NewsqqController_getNewNewsqq"];
  };
  "/api/toutiao": {
    /** 获取头条热榜 */
    get: operations["ToutiaoController_getToutiao"];
  };
  "/api/toutiao/new": {
    /** 获取头条热榜 - 最新数据 */
    get: operations["ToutiaoController_getNewToutiao"];
  };
  "/api/users": {
    /** 获取所有用户 */
    get: operations["UserController_findAll"];
    /** 创建新用户 */
    post: operations["UserController_create"];
  };
  "/api/users/{id}": {
    /** 获取单个用户 */
    get: operations["UserController_findOne"];
    /** 更新用户信息 */
    put: operations["UserController_update"];
    /** 删除用户 */
    delete: operations["UserController_delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  GirlController_getGirls: {
    responses: {
      /** @description 获取女孩信息成功 */
      200: never;
      /** @description 获取女孩信息失败 */
      500: never;
    };
  };
  /** 获取稀土掘金热榜 */
  JuejinController_getJuejin: {
    responses: {
      /** @description 获取稀土掘金热榜成功 */
      200: never;
      /** @description 获取稀土掘金热榜失败 */
      500: never;
    };
  };
  /** 获取最新稀土掘金热榜 */
  JuejinController_getNewJuejin: {
    responses: {
      /** @description 获取最新稀土掘金热榜成功 */
      200: never;
      /** @description 获取最新稀土掘金热榜失败 */
      500: never;
    };
  };
  /** 获取36氪热榜 */
  KrController_getKr: {
    responses: {
      /** @description 获取36氪热榜成功 */
      200: never;
      /** @description 获取36氪热榜失败 */
      500: never;
    };
  };
  /** 获取最新36氪热榜 */
  KrController_getNewKr: {
    responses: {
      /** @description 获取最新36氪热榜成功 */
      200: never;
      /** @description 获取最新36氪热榜失败 */
      500: never;
    };
  };
  /** 获取百度热搜榜 */
  BaiduController_getBaidu: {
    responses: {
      /** @description 获取百度热搜榜 */
      200: never;
    };
  };
  /** 获取百度热搜榜的最新数据 */
  BaiduController_getNewBaidu: {
    responses: {
      /** @description 获取百度热搜榜的最新数据 */
      200: never;
    };
  };
  /** 获取哔哩哔哩热门榜 */
  BilibiliController_getBilibili: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取知乎热榜 */
  ZhihuController_getZhihuHot: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取最新的知乎热榜 */
  ZhihuController_getZhihuHotNew: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取贴吧热议榜 */
  TiebaController_getTieba: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取最新的贴吧热议榜 */
  TiebaController_getNewTieba: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取澎湃热榜 */
  ThePaperController_getThePaper: {
    responses: {
      /** @description 获取成功 */
      200: never;
    };
  };
  /** 获取澎湃热榜 - 最新数据 */
  ThePaperController_getNewThePaper: {
    responses: {
      /** @description 获取成功 */
      200: never;
    };
  };
  /** 获取微博热搜 */
  WeiboController_getWeibo: {
    responses: {
      /** @description 获取成功 */
      200: never;
    };
  };
  /** 获取微博热搜 - 最新数据 */
  WeiboController_getNewWeibo: {
    responses: {
      /** @description 获取成功 */
      200: never;
    };
  };
  /** 获取少数派热榜 */
  SspaiController_getSspai: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取少数派热榜 - 最新数据 */
  SspaiController_getNewSspai: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取腾讯热点榜 */
  NewsqqController_getNewsqq: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取腾讯热点榜 - 最新数据 */
  NewsqqController_getNewNewsqq: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取头条热榜 */
  ToutiaoController_getToutiao: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取头条热榜 - 最新数据 */
  ToutiaoController_getNewToutiao: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 获取所有用户 */
  UserController_findAll: {
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 创建新用户 */
  UserController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description 创建成功 */
      201: never;
      /** @description 创建失败 */
      500: never;
    };
  };
  /** 获取单个用户 */
  UserController_findOne: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description 获取成功 */
      200: never;
      /** @description 获取失败 */
      500: never;
    };
  };
  /** 更新用户信息 */
  UserController_update: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description 更新成功 */
      200: never;
      /** @description 更新失败 */
      500: never;
    };
  };
  /** 删除用户 */
  UserController_delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description 删除成功 */
      204: never;
      /** @description 删除失败 */
      500: never;
    };
  };
}
